# Generated by Django 3.0 on 2020-01-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200103_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cplatforminstence',
            options={'managed': True},
        ),
    ]
