# Generated by Django 2.2.4 on 2020-01-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200103_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cplatforminstence',
            options={},
        ),
    ]
